---
- hosts: all 
  become: true

  tasks:
    - name: create oga user
      tags: always
      user:
        name: oga
        group: root
        shell: /bin/bash

    - name: creating user goddess
      tags: always
      user:
        name: goddess
        group: root
        shell: /bin/bash

    - name: Add ssh key for Oga
      tags: always
      authorized_key:
        user: oga
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHmiqEHubMUaftNkCM5cDYEaXhzods5bnSBnXws0jZWT ansible"

    - name: Add a sudoer file for oga
      tags: always
      copy:
        src: sudoer_oga
        dest: /etc/sudoers.d/oga
        owner: root
        group: root
        mode: 0440





- name: updating and installing packages
  hosts: web_servers
  become: true

  tasks: 
    - name: update repository
      package:
        update_cache: yes
      when: ansible_architecture == "Ubuntu" and ansible_distribution == "OracleLinux"

    - name: install  apache2
      package:
        name:
          - apache2
        state: latest
      when: ansible_architecture == "Ubuntu" 

    - name: install httpd and php
      package:
         name:
           - php
           - httpd
         state: latest
      when: ansible_distribution == "OracleLinux"

# plays for file servers 
- hosts: file_servers
  become: true
  tasks:

    - name: install Samba
      package:
        name: samba
        state: latest

    - name: install unzip
      package:
        name: unzip

    - name: Install OpenTofu
      unarchive:
        src: https://github.com/opentofu/opentofu/releases/download/v1.6.0-rc1/tofu_1.6.0-rc1_darwin_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

# plays for web servers
- hosts: web_servers
  become: true
  tasks:

    - name: Start httpd(Oracle linux)
      tags: apache, httpd,Oracle linux
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "OracleLinux"

    - name: change email address for admin (OracleLinux"
      tags: apache,httpd,OracleLinux
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin okunoyesouleiman@gmail.com
      when: ansible_distribution == "OracleLinux"
      register: httpd

    - name: Restart httpd
      tags: apache,OracleLinux,httpd
      service:
        name: httpd
        state: restarted
      when: httpd.changed
