---
- hosts: all
  become: true

  tasks:
    - name: update Repository
      apt:
        update_cache: yes

    - name: Remove Apache2 and php packages
      package:
        name:
         - httpd
         - php
         - apache2
         - libapache2-mod-php
        state: absent
      when: ansible_architecture == "Ubuntu" and ansible_distribution == "OracleLinux" 

